dmzx_imageupload_controller_upload:
    path: /imageupload
    defaults: { _controller: dmzx.imageupload.controller.upload:handle_imageupload }
dmzx_imageupload_controller_ucp_controller:
    path: /ucp_controller
    defaults: { _controller: dmzx.imageupload.ucp.controller:main }